name: CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        ls -l
        echo 'Docker login'
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
        echo 'Runing docker-compose'
        docker-compose start
        echo 'Done'
        
