name: CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Know IP Adress
      run: |
        apt install net-tools
        ipconfig
    - name: Build
      run: |
        ls -l
        echo 'down compose'
        docker-compose down
        echo 'Runing docker-compose'
        docker-compose up -d
        echo 'Done'
        
